#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

TELEGRIP_GIST_ID="${TELEGRIP_GIST_ID:-a84200f82fd9618213d05f27e1c255ff}"
export TELEGRIP_GIST_ID

command -v cloudflared >/dev/null || {
  echo "cloudflared is required: https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/downloads/"
  exit 2
}

HTTPS_LOG="$(mktemp)"
WS_LOG="$(mktemp)"
TELEGRIP_PID=""
HTTPS_PID=""
WS_PID=""

cleanup() {
  [ -z "$TELEGRIP_PID" ] || kill "$TELEGRIP_PID" 2>/dev/null || true
  [ -z "$HTTPS_PID" ] || kill "$HTTPS_PID" 2>/dev/null || true
  [ -z "$WS_PID" ] || kill "$WS_PID" 2>/dev/null || true
  rm -f "$HTTPS_LOG" "$WS_LOG"
  printf '%s\n' \
    '// Local mode leaves this empty. scripts/start_remote.sh replaces it at runtime.' \
    'window.TELEGRIP_WS_TUNNEL_HOSTNAME = "";' \
    > "$ROOT/web-ui/ws_config.js"
}
trap cleanup EXIT INT TERM

telegrip --no-viz "$@" &
TELEGRIP_PID=$!

cloudflared tunnel --url https://localhost:8443 --no-tls-verify >"$HTTPS_LOG" 2>&1 &
HTTPS_PID=$!
cloudflared tunnel --url https://localhost:8442 --no-tls-verify >"$WS_LOG" 2>&1 &
WS_PID=$!

get_url() {
  local log_file="$1"
  local url=""
  for _ in $(seq 1 45); do
    url="$(grep -Eo 'https://[a-z0-9-]+\.trycloudflare\.com' "$log_file" | grep -v 'api.trycloudflare.com' | awk 'NR==1' || true)"
    if [ -n "$url" ]; then
      printf '%s\n' "$url"
      return 0
    fi
    sleep 1
  done
  return 1
}

HTTPS_URL="$(get_url "$HTTPS_LOG")" || {
  echo "Timed out waiting for the HTTPS tunnel."
  exit 1
}
WS_URL="$(get_url "$WS_LOG")" || {
  echo "Timed out waiting for the WebSocket tunnel."
  exit 1
}
WS_HOST="${WS_URL#https://}"

printf '%s\n' \
  '// Generated by scripts/start_remote.sh; reset when it exits.' \
  "window.TELEGRIP_WS_TUNNEL_HOSTNAME = \"$WS_HOST\";" \
  > "$ROOT/web-ui/ws_config.js"

LAN_IP="$(hostname -I | awk '{print $1}')"
LOCAL_URL="https://${LAN_IP}:8443"
"$ROOT/scripts/publish_quest_link.sh" "$HTTPS_URL" "$LOCAL_URL"

echo "Remote Quest URL: $HTTPS_URL"
echo "Stable Quest bookmark: https://gist.github.com/$TELEGRIP_GIST_ID"
echo "Press Ctrl+C to stop Telegrip and both tunnels."
wait "$TELEGRIP_PID" "$HTTPS_PID" "$WS_PID"
